spring:
  datasource:
    url: jdbc:postgresql://77.234.215.138:30028/service_304
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    validate-on-migrate: true
    baselineOnMigrate: true

security:
  token-lifetime: 30m
